services:
  server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  web:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    env_file:
      - .env
    ports:
      - "6379:6379"
