services:
  server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    env_file:
      - .env
    ports:
      - "6379:6379"
