"""Fix parent id field in folder and note models

Revision ID: 3ab72fb3a9d0
Revises: 9ca099407d63
Create Date: 2025-08-27 09:28:33.076621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab72fb3a9d0'
down_revision: Union[str, Sequence[str], None] = '9ca099407d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
