"""Added deleted column to history server defualt 0

Revision ID: 5406b1b71d65
Revises: a5f74c966337
Create Date: 2025-09-01 15:53:06.192494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5406b1b71d65"
down_revision: Union[str, Sequence[str], None] = "a5f74c966337"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "History",
        sa.Column("deleted", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("History", "deleted")
    # ### end Alembic commands ###
