"""make tags' names unique

Revision ID: 59e08f095c0e
Revises: 5406b1b71d65
Create Date: 2025-09-17 08:31:17.416197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e08f095c0e'
down_revision: Union[str, Sequence[str], None] = '5406b1b71d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tags', type_='unique')
    # ### end Alembic commands ###
