"""Added error category and renamed message to context

Revision ID: 84d256d80b99
Revises: f68945ab79a2
Create Date: 2025-09-01 12:17:35.800282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84d256d80b99"
down_revision: Union[str, Sequence[str], None] = "f68945ab79a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Issues", sa.Column("context", sa.Text(), nullable=False))
    op.add_column("Issues", sa.Column("error_category", sa.String(), nullable=False))
    op.drop_column("Issues", "message")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Issues", sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_column("Issues", "error_category")
    op.drop_column("Issues", "context")
    # ### end Alembic commands ###
