"""Add deleted fields to Folder and Tag

Revision ID: 9ca099407d63
Revises: 5f3bf460c013
Create Date: 2025-08-27 08:32:10.347339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca099407d63'
down_revision: Union[str, Sequence[str], None] = '5f3bf460c013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Folders', sa.Column('deleted', sa.Integer(), nullable=False))
    op.add_column('Issues', sa.Column('deleted', sa.Integer(), nullable=False))
    op.add_column('Tags', sa.Column('deleted', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tags', 'deleted')
    op.drop_column('Issues', 'deleted')
    op.drop_column('Folders', 'deleted')
    # ### end Alembic commands ###
