"""Added deleted column to history

Revision ID: a5f74c966337
Revises: 84d256d80b99
Create Date: 2025-09-01 15:46:22.953439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a5f74c966337"
down_revision: Union[str, Sequence[str], None] = "84d256d80b99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("History", "deleted")
    # ### end Alembic commands ###
