"""Change the relationship between history and issues, the foreign key is in issues

Revision ID: afb1502c6309
Revises: 67cd3cda2e93
Create Date: 2025-09-01 09:00:51.608342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afb1502c6309"
down_revision: Union[str, Sequence[str], None] = "67cd3cda2e93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "Issues", "History", ["version_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Issues", type_="foreignkey")
    # ### end Alembic commands ###
