"""Add description to history table

Revision ID: b54fdadc6ec0
Revises: afb1502c6309
Create Date: 2025-09-01 09:14:40.696815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54fdadc6ec0'
down_revision: Union[str, Sequence[str], None] = 'afb1502c6309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('History', sa.Column('rev_description', sa.String(), nullable=False))
    op.add_column('History', sa.Column('note_title', sa.String(), nullable=False))
    op.add_column('History', sa.Column('note_content', sa.Text(), nullable=False))
    op.drop_column('History', 'content')
    op.drop_column('History', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('History', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('History', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('History', 'note_content')
    op.drop_column('History', 'note_title')
    op.drop_column('History', 'rev_description')
    # ### end Alembic commands ###
