"""Drop content_md column in history table

Revision ID: c3d0082e58a0
Revises: f87fe03582ed
Create Date: 2025-09-01 08:48:12.288545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d0082e58a0'
down_revision: Union[str, Sequence[str], None] = 'f87fe03582ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('History', 'issues_applied')
    op.add_column('Issues', sa.Column('version_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Issues', 'version_id')
    op.add_column('History', sa.Column('issues_applied', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
