"""Drop content_md column in history table

Revision ID: f87fe03582ed
Revises: 3ab72fb3a9d0
Create Date: 2025-09-01 08:42:52.837964

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f87fe03582ed"
down_revision: Union[str, Sequence[str], None] = "3ab72fb3a9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("History", "content_md")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "History",
        sa.Column("content_md", sa.TEXT(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
